---
title: "poverty project sample code"
author: "Yihan Wang"
output:
  word_document: default
  pdf_document: default
  html_document: default
Date: 08/15/2020
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(ggplot2)
library(rmarkdown)

poverty <- read_csv("C:/Users/Yihan/Desktop/China House/2020-08/Poverty_ChinaHouse.csv")
```

### Time series analyses - line chart
```{r}
colnames(poverty)[which(names(poverty) == "Country Name")] <- "CountryName"
colnames(poverty)[which(names(poverty) == "Indicator Name")] <- "IndicatorName"

poverty_sub <- poverty %>%
  subset(CountryName == "China" | CountryName == "United States") %>%
  filter(IndicatorName == "GINI index (World Bank estimate)") %>%
  gather("year", "value", "1996":"2019") %>%
  filter(!is.na(value)) %>%
  select(CountryName, IndicatorName, year, value)

poverty_sub$year = as.numeric(poverty_sub$year)

ggplot(poverty_sub, aes(x = year, y = value, color = CountryName)) +
  geom_point() +
  geom_line() +
   labs(title = "GINI index of China and the US",
       subtitle = "three-year data",
       x = "Year", 
       y = "Gini Index",
       color = "Country") 

```
### time series analyses - bar chart 
```{r}
colnames(poverty)[which(names(poverty) == "Country Name")] <- "CountryName"
colnames(poverty)[which(names(poverty) == "Indicator Name")] <- "IndicatorName"

poverty_sub <- poverty %>%
  subset(CountryName == "China" | CountryName == "United States") %>%
  filter(IndicatorName == "GINI index (World Bank estimate)") %>%
  gather("year", "value", "1996":"2019") %>%
  subset(year == "2010" | year == "2013" | year == "2016") %>%
  filter(!is.na(value)) %>%
  select(CountryName, IndicatorName, year, value)

poverty_sub$year = as.numeric(poverty_sub$year)

ggplot(poverty_sub, aes(x = year, y = value)) +
  geom_histogram(stat= "identity") +
  facet_grid(~CountryName) +
  scale_x_continuous(breaks = c(2010, 2013, 2016), 
                       labels = c("2010","2013","2016")) +
  coord_cartesian(ylim = c(35,45)) +
  labs(title = "GINI index of China and the US",
       subtitle = "three-year data",
       x = "Year", 
       y = "GINI Index") 

```

### GINI index, global 2019 

```{r}
colnames(poverty)[which(names(poverty) == "Country Name")] <- "CountryName"
colnames(poverty)[which(names(poverty) == "Indicator Name")] <- "IndicatorName"
colnames(poverty)[which(names(poverty) == "2018")] <- "Year2018"

#head(poverty)

global_gini <- 
  poverty %>%
  filter( IndicatorName == "GINI index (World Bank estimate)") %>%
  select( CountryName, IndicatorName, "Year2018") %>%
  na.omit("2018") 

global_gini %>%
  summarize(countries = n(),
            max_gini = max(Year2018),
            min_gini = min(Year2018),
            mean_gini = mean(Year2018)) %>%
  mutate(thailand_gini = global_gini$Year2018[24])
```

### single country multiple indicators 
```{r}
poverty_china <- poverty %>%
  subset(CountryName == "China") %>%
  filter(IndicatorName == "Income share held by lowest 20%" | IndicatorName == "Income share held by highest 20%" | IndicatorName == "GINI index (World Bank estimate)") %>%
  gather("year", "value", "1996":"2019") %>%
  na.omit()

poverty_china$year = as.numeric(poverty_china$year)

ggplot(poverty_china, aes(x = year, y = value, color = IndicatorName)) + 
  geom_line()

```
